config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :artists do
  resources :portfolios

 #get 'portfolios', to: 'portfolios#something_else', as: 'portfolios'
  end

root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates_presence_of :name
  validates_presence_of :shop

  has_many :portfolios, dependent: :destroy

end

app/models/porfolio.rb
class Porfolio < ApplicationRecord
  validates_presence_of :style

  belongs_to :artist

end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  validates_presence_of :style
  serialize :photo_urls
  belongs_to :artist
end


# in your controller
# @portfolio = Portfolio.find(params[:id])


# in your view
# <h1> Style: <%= @portfolio.style %> </h1>
# <% @portfolio.photo_urls.each do |url| %>
#   <img src=<%= url %> />
# <% end %>

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
         :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/artist_controller.rb
class ArtistController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = Artist.all
  end

  def show
  end

  def new
    @artist = Artist.new
  end

  def edit
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      redirect_to @artist
    else
      render :new
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_to @artist
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end


  private
    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artist_params
      params.require(:artist).permit(:name, :description, :shop)
    end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = Artist.all
  end

  def show
  end

  def new
    @artist = Artist.new
  end

  def edit
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      redirect_to @artist
    else
      render :new
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_to @artist
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end


  private
    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artist_params
      params.require(:artist).permit(:name, :description, :shop, :schedule)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
#before_action :set_artist

  def index
  end

  def show
    @artist = Artist.find(params[:artist_id])

    @portfolio = @artist.portfolios.find(params[:id])
  end


private

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") 
    else 
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/artists/_form.html.erb
<%= form_for artist do |f| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "name" %>
    <%= f.text_field :name %>
  </div>

 <div class="field">
    <%= f.label "shop" %>
    <%= f.text_field :shop %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :schedule %>
    <%= f.text_field :schedule %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  
<%= link_to 'Back to Artists', artists_path %>

<% end %>

app/views/artists/index.html.erb
<div>
  <span class='#dd2c00 deep-orange-text text-accent-4'>
<h1>Artists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Shop</th>
      <th>Schedule</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= artist.shop %></td>
        <td><%= artist.schedule %></td>
        <td><%= link_to 'Show Artist', artist %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />
</span>
</div>

<!-- %= link_to 'New Artist', new_artist_path % -->

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

app/views/artists/show.html.erb
<div>
  <span class='#dd2c00 deep-orange-text text-accent-4'>
<h1>Artist: <%= @artist.name %> </h1>

<% unless @artist.shop.empty? %>
    <p>
      <strong>Shop:</strong>
      <%= @artist.shop %>
    </p>
<% end %>

<% unless @artist.description.empty? %>
    <p>
      <strong>Description:</strong>
      <%= @artist.description %>
    </p>
<% end %>

<% unless @artist.schedule.empty? %>
    <p>
      <strong>Schedule:</strong>
      <%= @artist.schedule %>
    </p>
    <hr />
<% end %>

<% if @artist.portfolios.any? %>
    <h5> Portfolios </h5>
    <div class="row">

      <% @artist.portfolios.each do |portfolio| %>

        <ul class="collection">
        <li class="collection-item avatar">
        <span class="title"><%= link_to portfolio.style, artist_portfolio_path(@artist, portfolio) %></span>


        </li>
        </ul>

      <% end %>
    </div>

 <% else %>
  <h5>No Portfolios Found</h5>
<% end %>

<%= link_to 'Show All Artists', artists_path %> |
</span>
</div>

app/views/home/index.html.erb
<div>
  <span class='#dd2c00 deep-orange-text text-accent-4'>
    <h1>Welcome to InkFace</h1>
      <h5>SLC's best place to find local artists!</h5>
        <hr />
<body>
    <p>To begin your search click either the Artist or the Styles button.</p>
  <img src="https://news.bme.com/wp-content/uploads/2008/05/shadeboxes.jpg" alt="Shoulder View of Tattoo Being Applied" style="width:250px;height:167px;">
</body>
</span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InkFace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render(partial: 'shared/navbar') %>
      <div class='container'>
        <%= yield %>
      </div>
  </body>
</html>

app/views/portfolios/exit.html.erb
<h1>Portfolios#exit</h1>
<p>Find me in app/views/portfolios/exit.html.erb</p>

app/views/portfolios/index.html.erb
<div>
  <span class='#dd2c00 deep-orange-text text-accent-4'>
    <h1>Portfolios</h1>
<table>
  <thead>
    <tr>
      <th>Artist</th>
      <th>Style</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portfolios.each do |portfolio| %>
      <tr>
        <td><%= portfolio.artist_id %> </td>
        <td><%= portfolio.style %></td>
        <td><%= link_to 'Show Portfolio', portfolio %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</span>
</div>

<%= link_to 'Show Artists', artists_path %> |
<%= link_to 'Home', root_path %> |

app/views/portfolios/show.html.erb
<div>
  <span class='#dd2c00 deep-orange-text text-accent-4'>
 <h1> Style: <%= @portfolio.style %> </h1>
<% @portfolio.photo_urls.each do |url| %>
   <img src=<%= url %> />
 <% end %>
 </span>
 </div>
 

app/views/shared/_form.html.erb
<!-- <% if @address.errors.any? %>
  <h4> <%= @address.errors.count %> Errors Saving The Address </h4>
  <% @address.errors.full_messages.each do |message| %>
    <h6 class='text-danger'> <%= message %> </h6>
  <% end %>
<% end %>

<%= form_for [@location, @address], html: { class: 'form-horizontal'} do |f| %>

  <div class="form-group">
    <%= f.label :location_address, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :location_address, required: true, class: 'form-control', placeholder: 'Type Location Address Here' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">

      <%= f.text_area :description, class: 'form-control', placeholder: 'Add Description of Location' %>



    </div>
  </div>

  <div class='text-center'>
    <%= f.submit nil, class: 'btn btn-primary' %>
  </div>
<% end %> -->

app/views/shared/_navbar.html.erb
<nav class="nav-extended #000000 black">
  <div class="container-fluid">

    <div class="nav-wrapper">
      <a href="/" class="brand-logo">Inkface</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li>
          <% if user_signed_in? %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
          <% end %>
        </li>
      </ul>
    </div>
    <div class="row">
  <div class="col s12">
    <ul class="tabs #000000 black">
      <li class="tab col s3 offset-s2 btn btn-floating pulse #4a148c purple darken-4">
        <a href="/artists">
          <span class='#fafafa grey-text text-lighten-5'>Artists</span>
        </a>
      </li>
      <li class="tab col s3 offset-s2 btn btn-floating pulse #4a148c purple darken-4">
        <a href="Styles">
          <span class='#fafafa grey-text text-lighten-5'>Styles</span>
        </a>
      </li>
    </ul>
  </div><!-- /.container-fluid -->
</nav>